# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: self-hosted
  Demands:
  - agent.name -equals 'MSI-laptop'

steps:
- script: |
    docker exec -it postgres_container  pg_dump -h localhost -U postgres test-database -f postgres-backup-plantext
    docker cp postgres_container:/postgres-backup-plantext.
  displayName: 'Dump databaseName: test-database'

- task: CopyFiles@2
  displayName: 'Copy file to Artifact: PostgresBackupDatabase'
  inputs:
    Contents: ./postgres-backup-plantext
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - script: |
#     rm ./postgres-backup-plantext 
#     docker exec -it postgres_container rm ./postgres-backup-plantext
#   displayName: 'Delete temp file'