# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: self-hosted
  Demands:
  - agent.name -equals 'MSI-laptop'

steps:
- script: |
    docker exec -i postgres_container pg_dump -h localhost -U postgres test-database -f postgres-backup-plantext
    docker cp postgres_container:/postgres-backup-plantext postgres-backup-plantext
  displayName: 'Dump databaseName: test-database'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/postgres-backup-plantext
    artifactName: PostgresBackupDatabase

- script: |
    pwd
    ls -al
    del ./postgres-backup-plantext 
    docker exec -i postgres_container rm ./postgres-backup-plantext
  displayName: 'Delete temp file'